.\" Début de la page de manuel
.\" Ceci est un commentaire, il ne sera pas affiché dans la sortie finale
.\" .TH définit le titre de la page, la section, la date, la version, et un commentaire additionnel
.TH CPPCLASS 1 "Avril 2025" "1.0" "Page de manuel pour cppclass"

.\" Section NAME (Nom de la commande et brève description)
.SH NAME
cppclass \- Chargement d'un template de class cpp

.SH SYNOPSIS
.B cppclass
.RI [ options ] " <destination_folder> [branch_type] [git_url]"

.\" Section DESCRIPTION (Description détaillée de ce que fait la commande)
.SH DESCRIPTION
.B cppclass
est une commande permettant de crée directement une class a partir d'un template.

.LP
Voici un exemple d'exécution avec arguments : cppclass
.TP
.B arg1
Nom de la class a créer
.\" 

.\" Section EXAMPLES (Exemples pratiques d'utilisation)
.SH EXAMPLES
Voici un exemple pratique d'utilisation de la commande cppclass :

.TP
.B cppclass Contact
Créer les fichiers Contact.cpp et Contact.hpp 
.\"

.\" Section AUTHOR
.SH AUTHOR
nchetela <nchetela@student.42lausanne.ch>
.\"
